### ISSUE TITLE
Creating Channels class

### ISSUE THREAD

**Issue by Themimitoof** [hivelink/Hivelink_websocket#1]
This class contain a simple way to listen a _channel_ using a path like a route in ExpressJS. Example:
```javascript
ws.channel("/chat/1", (data) => {
    // making something
}
```

The routes system should, as much as possible, inherit the same syntax and flexibility that ExpressJS now offers. 

The class need to contain methods to broadcast in a specific channel or the entire network (for that, is pretty easy, a good example are available in the _ws_ documentation).

I don't know if is a good idea and if is really useful, is making a method to get info when a user are connected to a channel. _Need to be debated for this point._

To keep the multiples informations purposed by the main module about the websocket, I think is good to send in callback the _ws_ and the _req_ when a new event. An example of what I think:
```javascript
{
  data: "message",
  _ws: { ws, req }
}
```

# ToDo

- [ ]  Make HiveLinkWSChannels class
- [ ]  Make channel method
- [ ]  Make "route parser"
- [ ]  Make broadcast method
- [ ] _Optionnal_ Make _conn_ method.
